# Generated by Django 5.2.6 on 2025-09-25 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('PN', 'Paneer'), ('MS', 'Milkshake'), ('IC', 'Ice-Creams'), ('CR', 'Crud'), ('CZ', 'Cheese'), ('ML', 'MILK'), ('LS', 'Lassi')], max_length=2),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Karnataka', 'Karnataka'), ('Daman & Diu', 'Daman & Diu'), ('Delhi', 'Delhi'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Telangana', 'Telangana'), ('Gujarat', 'Gujarat'), ('Nagaland', 'Nagaland'), ('Chhattisgarh', 'Chhattisgarh'), ('Puducherry', 'Puducherry'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Goa', 'Goa'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Sikkim', 'Sikkim'), ('Kerala', 'Kerala'), ('Tripura', 'Tripura'), ('Assam', 'Assam'), ('Rajasthan', 'Rajasthan'), ('Bihar', 'Bihar'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Mizoram', 'Mizoram'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Odisha', 'Odisha'), ('Lakshadweep Islands', 'Lakshadweep Islands'), ('Meghalaya', 'Meghalaya'), ('Haryana', 'Haryana'), ('Punjab', 'Punjab'), ('Manipur', 'Manipur'), ('Chandigarh', 'Chandigarh'), ('Tamil Nadu', 'Tamil Nadu'), ('Jharkhand', 'Jharkhand'), ('Uttarakhand', 'Uttarakhand'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('West Bengal', 'West Bengal'), ('Andhra Pradesh', 'Andhra Pradesh')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
