# Generated by Django 5.2.6 on 2025-09-25 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'MILK'), ('MS', 'Milkshake'), ('CR', 'Crud'), ('LS', 'Lassi'), ('PN', 'Paneer'), ('IC', 'Ice-Creams'), ('CZ', 'Cheese'), ('GH', 'Ghee')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Meghalaya', 'Meghalaya'), ('Tripura', 'Tripura'), ('Maharashtra', 'Maharashtra'), ('Daman & Diu', 'Daman & Diu'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('West Bengal', 'West Bengal'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Kerala', 'Kerala'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Puducherry', 'Puducherry'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Goa', 'Goa'), ('Sikkim', 'Sikkim'), ('Mizoram', 'Mizoram'), ('Karnataka', 'Karnataka'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Delhi', 'Delhi'), ('Lakshadweep Islands', 'Lakshadweep Islands'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Gujarat', 'Gujarat'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Telangana', 'Telangana'), ('Nagaland', 'Nagaland'), ('Chhattisgarh', 'Chhattisgarh'), ('Tamil Nadu', 'Tamil Nadu'), ('Uttarakhand', 'Uttarakhand'), ('Manipur', 'Manipur'), ('Bihar', 'Bihar'), ('Haryana', 'Haryana'), ('Assam', 'Assam'), ('Odisha', 'Odisha'), ('Jharkhand', 'Jharkhand'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Chandigarh', 'Chandigarh')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
